import Head from "next/head";
import {
    AiFillTwitterCircle,
    AiFillLinkedin,
    AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";

import deved from "../public/dev-ed-wave.png";

import wp1 from "../public/wp1.png";
import wp2 from "../public/wp2.png";
import wp3 from "../public/wp3.png";
import wp4 from "../public/wp4.png";

import reactIcon from "../public/react-icon.png";
import nextIcon from "../public/Nextjs-logo.svg";
import bootstrap from "../public/bootstrap-icon.png";
import tailwind from "../public/tailwindcss-icon.png";
import htmlIcon from "../public/html-icon.png";
import cssIcon from "../public/css-icon.png";
import jsIcon from "../public/js-icon.png";
import css from "styled-jsx/css";

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);

    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Advait's Portofolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between dark:text-white">
                        <h1 className="font-burtons text-xl">
                            developedbyAdvait
                        </h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className=" cursor-pointer text-2xl"
                                />
                            </li>
                            <li>
                                <a
                                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                                    href="#"
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center p-10 py-10">
                        <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
                            Advait Suresh
                        </h2>
                        <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
                            Front-End Developer
                        </h3>
                        <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                            A Front-end developer with knowledge and experience
                            with core and new front end technologies. Passionate
                            about designing user-friendly interfaces and
                            enhancing user experience through creative
                            problem-solving. Skilled in turning design concepts
                            into reality. Continuously expanding knowledge with
                            the latest web development technologies.
                        </p>
                        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                            <AiFillTwitterCircle />
                            <AiFillLinkedin />
                            <AiFillYoutube />
                        </div>
                        <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
                            <Image
                                src={deved}
                                layout="fill"
                                objectFit="cover"
                                alt="icon"
                            />
                        </div>
                    </div>
                </section>
                <section>
                    <div>
                        <h3 className="text-3xl py-1 dark:text-white ">
                            My Tech Stack
                        </h3>
                    </div>
                    <div className="lg:flex gap-10">
                        <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
                            <div className="flex flex-row justify-center gap-6">
                                <Image
                                    src={htmlIcon}
                                    width={100}
                                    height={100}
                                    alt="icon"
                                />
                                <Image
                                    src={cssIcon}
                                    width={100}
                                    height={100}
                                    alt="icon"
                                />
                                <Image
                                    src={jsIcon}
                                    width={100}
                                    height={100}
                                    alt="icon"
                                />
                            </div>
                            <h3 className="text-lg font-medium pt-8 pb-2  ">
                                Basics
                            </h3>
                            <p className="text-gray-800 py-1">Html</p>
                            <p className="text-gray-800 py-1">CSS</p>
                            <p className="text-gray-800 py-1">JavaScript</p>
                        </div>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                            <div className="flex flex-row justify-center gap-6">
                                <Image
                                    src={bootstrap}
                                    width={100}
                                    height={100}
                                    alt="icon"
                                />
                                <Image
                                    src={tailwind}
                                    width={100}
                                    height={100}
                                    alt="icon"
                                />
                            </div>
                            <h3 className="text-lg font-medium pt-8 pb-2 ">
                                CSS Frameworks
                            </h3>
                            <p className="text-gray-800 py-1">Bootstrap</p>
                            <p className="text-gray-800 py-1">Tailwind CSS</p>
                        </div>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                            <div className="flex flex-row justify-center gap-6">
                                <Image
                                    src={reactIcon}
                                    width={100}
                                    height={100}
                                    alt="icon"
                                />
                                <Image
                                    src={nextIcon}
                                    width={100}
                                    height={100}
                                    alt="icon"
                                />
                            </div>
                            <h3 className="text-lg font-medium pt-8 pb-2 ">
                                JavaScript Frameworks
                            </h3>
                            <p className="text-gray-800 py-1">React JS</p>
                            <p className="text-gray-800 py-1">Next JS</p>
                        </div>
                    </div>
                </section>
                <section className="py-10">
                    <div>
                        <h3 className="text-3xl py-1 dark:text-white ">
                            Portofolio
                        </h3>
                    </div>
                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                        <div className="basis-1/3 flex-1 ">
                            <Link
                                href={`https://advait-04.github.io/my-anime-taste/`}
                            >
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={wp1}
                                    alt="icon"
                                />
                            </Link>
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Link
                                href={`https://advait-04.github.io/notes-app/`}
                                target="_blank"
                            >
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={wp2}
                                    alt="icon"
                                />
                            </Link>
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Link
                                href={`https://advait-04.github.io/tenzies-game/`}
                            >
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={wp3}
                                    alt="icon"
                                />
                            </Link>
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Link
                                href={`https://advait-04.github.io/meme-generator/`}
                            >
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={wp4}
                                    alt="icon"
                                />
                            </Link>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    );
}
